apiVersion: apps.paia.tech/v1alpha1
kind: HotStandbyDeployment
metadata:
  name: hsd-sample-http
  namespace: default
spec:
  idleTarget: 3
  minReplicas: 0
  maxReplicas: 50
  selector:
    matchLabels:
      app: hsd-sample
  busyProbe:
    mode: http
    http:
      port: 8080
      path: /busy
      successIsBusy: true
      timeoutSeconds: 1
      periodSeconds: 10
  podTemplate:
    metadata:
      labels:
        app: hsd-sample
    spec:
      containers:
        - name: app
          image: ghcr.io/your-org/your-app:latest
          ports:
            - name: http
              containerPort: 8080
